name: deploy-dev
on:
  push:
    branches:
      - develop
      - feature/issue000-check-gh-pages
# permissions:
#   contents: write

jobs:
  deploy-dev:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Action for Yarn
        uses: Borales/actions-yarn@v3.0.0
        with:
          persist-credentials: false

      - name: Build
        run: |
          sudo rm -rf node_modules
          sudo yarn install
          yarn rm
          sudo yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ADMIN }}
          FOLDER: build # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
