name: renovate
on:
  workflow_dispatch:
    schedule:
      # JST Mon~Fri action on 12:00
      - cron: '0 3 * * 0-4'

env:
  RENOVATE_REPOSITORIES: ${{ github.repository }}
  RENOVATE_USERNAME: ${{ github.repository_owner }}
  RENOVATE_GIT_AUTHOR: 'Renovate Bot <bot@renovateapp.com>'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_ACCESS_TOKEN }}
