name: test
on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'renovate/**'

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # "GitHub Action for npx" is only supported [macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Action for npx
        uses: mikeal/npx@v2.0.0

      - id: prettier-check
        run: npx prettier --check .
        shell: bash

      - name: Extract branch name
        shell: bash
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_REF#refs/heads/}
          echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: extract_branch

      - name: Print branch name
        env:
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
        run: echo $BRANCH_NAME

      - name: Print branch name2
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: echo $BRANCH_NAME

  for-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          ['2.7', '3.7', '3.8', '3.9', '3.10', 'pypy2.7', 'pypy3.8']
        exclude:
          - os: macos-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.6'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Test-Run Python File
        run: python feature/tools/test.py
