name: test
on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: GitHub Action for npx
        uses: mikeal/npx@1.0.0

      - id: prettier-check
        run: npx prettier --check .
        shell: bash
